from spec_validator import maximize_fitness

# -----------------------------------------------------------------------
# Auto-generated by DynAlloyToFandango for program 'busquedaSecuencial'.
# Types: Bool, Int, Elem, Seq
# Params: s:Seq, elem:Elem, out:Bool
#
# Guarantees enforced by construction:
#   1. Every post-condition atom has the exact shape
#      <param>' <relation> <expr>: only primed parameters may
#      appear on the left-hand side of a relation, never unprimed
#      program variables (e.g. s, elem, out) or bound qvars.
#   2. Each program parameter's primed self-equality is fixed in the
#      formula tail (e.g. s' = s') so every primed parameter appears
#      in every generated formula even when unconstrained.
#   3. Quantifier nesting is capped at depth 1; only one qvar (i0).
# -----------------------------------------------------------------------

<start> ::= <formula>


 <formula> ::= <expr> " and s' = s' and elem' = elem' and out' = out'"

<expr> ::=   <guard> " implies "  <s_primed_rel>	 | <s_primed_rel>	 |  <guard> " implies "  <elem_primed_rel>	 | <elem_primed_rel>	 |  <guard> " implies "  <out_primed_rel>	 | <out_primed_rel>	 

 <guard> ::= <Int_rel> |  <expr_l1> 

 <expr_l1> ::=  "(" <expr_l2> " " <binop> " " <expr_l2> ")"	 | <unop> "(" <expr_l2> ")"	 | <quant_expr_l1>	          | <s_rel>	          | <elem_rel>	          | <out_rel>	

 <expr_l2> ::=  <Int_rel> 

 <binop> ::= "and" | "or" | "implies" | "iff"

 <unop>  ::= "not"


 <quant_expr_l1> ::= "(" <quantifier> " " <qvar> ":Int |" <qbody_l1> ")"
 where str(<qvar>) in str(<qbody_l1>)

 <qbody_l1> ::= "(" <qexpr_l2> " " <binop> " " <qexpr_l2> ")"	 | <unop> "(" <qexpr_l2> ")"	          | <s_rel>	          | <elem_rel>	          | <out_rel>	

 <qexpr_l2> ::=  <qInt_rel> 

 <qInt_rel> ::= "(" <qInt_term> ")" " = " "(" <qInt_term> ")"	          | "(" <qInt_term> ")" " != " "(" <qInt_term> ")"	          | "lte[" <qInt_scalar_term> "," <qInt_scalar_term> "]"	          | "gte[" <qInt_scalar_term> "," <qInt_scalar_term> "]"	          | "lt[" <qInt_scalar_term> "," <qInt_scalar_term> "]"	          | "gt[" <qInt_scalar_term> "," <qInt_scalar_term> "]"


 <quantifier> ::= "some" | "all" | "no" | "one"

 <qvar>       ::= "i0"



 <s_primed_rel> ::= "(" "s'" ")" " = " "(" <Seq_term> ")"	 | "s'" " != " "(" <Seq_term> ")"	 | "s'" " in " "(" <Seq_term> ")"	 | "s'" " !in " "(" <Seq_term> ")"	

 <elem_primed_rel> ::= "(" "elem'" ")" " = " "(" <Elem_term> ")"	 | "elem'" " != " "(" <Elem_term> ")"	 | "elem'" " in " "(" <Elem_term> ")"	 | "elem'" " !in " "(" <Elem_term> ")"	

 <out_primed_rel> ::= "(" "out'" ")" " = " "(" <Bool_term> ")"	 | "out'" " != " "(" <Bool_term> ")"	 | "out'" " in " "(" <Bool_term> ")"	 | "out'" " !in " "(" <Bool_term> ")"	

 <Int_rel> ::= "(" <Int_term> ")" " = " "(" <Int_term> ")"	          | "(" <Int_term> ")" " != " "(" <Int_term> ")"	          | "lte[" <Int_scalar_term> "," <Int_scalar_term> "]"	          | "gte[" <Int_scalar_term> "," <Int_scalar_term> "]"	          | "lt[" <Int_scalar_term> "," <Int_scalar_term> "]"	          | "gt[" <Int_scalar_term> "," <Int_scalar_term> "]"



 <s_rel> ::= "(" "s" ")" " = " "(" <Seq_term> ")"	 | "s" " != " "(" <Seq_term> ")"	 | "s" " in " "(" <Seq_term> ")"	 | "s" " !in " "(" <Seq_term> ")"	

 <elem_rel> ::= "(" "elem" ")" " = " "(" <Elem_term> ")"	 | "elem" " != " "(" <Elem_term> ")"	 | "elem" " in " "(" <Elem_term> ")"	 | "elem" " !in " "(" <Elem_term> ")"	

 <out_rel> ::= "(" "out" ")" " = " "(" <Bool_term> ")"	 | "out" " != " "(" <Bool_term> ")"	 | "out" " in " "(" <Bool_term> ")"	 | "out" " !in " "(" <Bool_term> ")"	

 <Bool_term> ::= <Bool_var>	                | <Bool_const>

 <Bool_var> ::= "out"

 <Bool_const> ::= "boolean/True" | "boolean/False"


 <Int_term> ::= <Seq_idx_join>	               | <Seq_length_join>

 <qInt_term> ::= <Seq_idx_join>	               | <Seq_length_join>	 | <qvar>

 <Int_const> ::= "0" | "1" | "2" | "3" | "4" | "5"


 <Elem_term> ::= <Elem_var>	                | <Seq_at_join>

 <Elem_var> ::= "elem"


 <Seq_term> ::= <Seq_var>

 <Seq_var> ::= "s"


 <Int_scalar_term> ::= <Int_const>	               | <Seq_length_join>


 <qInt_scalar_term> ::= <Int_const>	| <Seq_length_join> 	 | 	 <qvar>


 <Seq_idx_join> ::= "(" <Seq_var> ")" " . " "(" "(this/Seq <: idx)" ")"

 <Seq_length_join> ::= "(" <Seq_var> ")" " . " "(" "(this/Seq <: length)" ")"

 <Seq_at_join> ::= "(" <Int_term> ")" " . " "(" "(" <Seq_var> ")" " . " "(" "(this/Seq <: at)" ")" ")"

  where int(maximize_fitness(str(<start>))) >= 40